# Generated by Django 4.1.5 on 2024-04-04 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(default='', max_length=50)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(default='')),
                ('slug', models.CharField(default='', max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='str_backend.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('post_view_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('post', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='str_backend.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='str_backend.post')),
            ],
        ),
    ]
