# Generated by Django 4.1.5 on 2024-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
