# Generated by Django 4.1.5 on 2024-04-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0003_alter_category_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='post_view_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
