# Generated by Django 4.1.5 on 2024-04-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0005_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
