# Generated by Django 4.1.5 on 2024-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0006_alter_post_content_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
