# Generated by Django 4.1.5 on 2024-04-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0007_category_total_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PostViews',
        ),
    ]
