# Generated by Django 4.1.5 on 2024-04-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0008_post_total_views_alter_category_total_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('emaill', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
