# Generated by Django 4.1.5 on 2024-04-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('str_backend', '0010_alter_emaillist_emaill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='emaill',
            new_name='email',
        ),
    ]
